[package]
name = "rusk"
version = "0.1.0"
authors = ["Victor Lopez <victor@dusk.network>"]
edition = "2018"

[dependencies]
tonic = "^0.1"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
tracing = "0.1"
tracing-subscriber = "0.1"
clap = "2.33"
prost = "0.6"
rusk-vm = { git = "ssh://git@github.com/dusk-network/rusk-vm.git", branch = "transfer" }
phoenix-abi = { git = "ssh://git@github.com/dusk-network/phoenix-abi.git", branch = "conversions" }
kelvin = "0.11.2"
bytehash = "0.2"
hex = "^0.4"

[dependencies.phoenix]
git = "ssh://git@github.com/dusk-network/phoenix.git"
branch = "plonk"

[build-dependencies]
tonic-build = { version = "0.1", default-features = false, features = ["transport"] }
