[package]
name = "rusk"
version = "0.1.0"
authors = ["Victor Lopez <victor@dusk.network>"]
edition = "2018"

[dependencies]
tonic = "^0.1"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
tracing = "0.1"
tracing-subscriber = "0.1"
clap = "2.33"
prost = "0.6"
rusk-vm = { path = "../rusk-vm" }
dusk-abi = { path = "../rusk-vm/dusk-abi" }
phoenix-abi = { path = "../phoenix-abi" }
kelvin = "0.9"
bytehash = "0.2"

[dependencies.phoenix]
git = "ssh://git@github.com/dusk-network/phoenix.git"
branch = "cleanup"
