[package]
name = "rusk"
version = "0.1.0"
authors = [
  "CPerezz <carlos@dusk.network>", 
  "zer0 <matteo@dusk.network>", 
  "Victor Lopez <victor@dusk.network>",
  "Jules de Smit <jules@dusk.network>",
  "Luke Pearson <luke@dusk.network>"
]
edition = "2018"
autobins = false

[lib]
name = "rusk"
path = "src/lib/lib.rs"

[[bin]]
name = "rusk"
path = "src/bin/main.rs"

[dependencies]
tonic = "0.3"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", branch = "min_nost", features = ["default","canon"]}
dusk-plonk = "0.3.4"
dusk-blindbid = {git = "https://github.com/dusk-network/dusk-blindbid", branch = "update_version", features = ["canon"]}
dusk-pki = {git = "https://github.com/dusk-network/dusk-pki/", branch = "update_pki"}
phoenix-core = { git = "https://github.com/dusk-network/phoenix-core", branch = "canon_featured", features = ["canon"]}
tracing = "0.1"
tracing-subscriber = "0.2"
clap = "2.33.3"
prost = "0.6"
kelvin = "0.19.0"
kelvin-radix = "0.11.0"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
thiserror = "1.0"
anyhow = "1.0"
rustc_tools_util = "0.2"
tower = "0.3"
rand = "0.7.0"
bincode = "1.3.1"
lazy_static = "1.4"
rusk-profile = { path = "./profile" }
canonical_host = "0.4"


[build-dependencies]
tonic-build = "0.3"
rustc_tools_util = "0.2"
dusk-plonk = "0.3.4"
dusk-blindbid = {git = "https://github.com/dusk-network/dusk-blindbid", branch = "update_version"}
anyhow = "1.0"
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", branch = "min_nost", features = ["default","canon"]}
dusk-pki = {git = "https://github.com/dusk-network/dusk-pki/", branch = "update_pki"}
phoenix-core = { git = "https://github.com/dusk-network/phoenix-core", branch = "canon_featured", features = ["canon"]}
kelvin = "0.19.0"
nstack = "0.6.0"
rand = "0.7"
bincode = "1.3.1"
bid-circuits = {path ="./contracts/bid/circuits"}
transfer-circuits = {path ="./contracts/transfer/circuits"}
rusk-profile = { path = "./profile" }
lazy_static = "1.4"
canonical_host = "0.4"
