[package]
name = "rusk"
version = "0.1.0"
authors = ["CPerezz <carlos@dusk.network>", "zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network>"]
edition = "2018"
autobins = false

[lib]
name = "rusk"
path = "src/lib/lib.rs"

[[bin]]
name = "rusk"
path = "src/bin/main.rs"

[dependencies]
tonic = "0.3"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
blind_bid = {git = "https://github.com/dusk-network/dusk-blindbid", branch = "blindbid_service_edits"}
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.6.4"}
dusk-plonk = "0.2.9"
tracing = "0.1"
tracing-subscriber = "0.2"
clap = "2.33.3"
prost = "0.6"
kelvin = "0.18"
kelvin-radix = "0.10"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
thiserror = "1.0"
anyhow = "1.0"
rustc_tools_util = "0.2"
tower = "0.3"

[build-dependencies]
tonic-build = "0.3"
rustc_tools_util = "0.2"


