[package]
name = "rusk"
version = "0.1.0"
authors = ["Victor Lopez <victor@dusk.network>"]
edition = "2018"

[lib]
name = "rusk"
path = "src/lib/lib.rs"

[[bin]]
name = "rusk"
path = "src/bin/main.rs"

[dependencies]
tonic = "0.3"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
tracing = "0.1"
tracing-subscriber = "0.2"
clap = "2.33.3"
prost = "0.6"
kelvin = "0.18"
kelvin-radix = "0.10"
thiserror = "1.0"
anyhow = "1.0"
rustc_tools_util = "0.2"

[build-dependencies]
tonic-build = "0.3"
rustc_tools_util = "0.2"

