[package]
name = "bid-circuits"
version = "0.1.0"
authors = ["Jules de Smit <jules@dusk.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.0"
dusk-plonk = "0.3.3"
plonk_gadgets = {git = "https://github.com/dusk-network/plonk_gadgets", tag = "v0.4.3"}
dusk-blindbid = { git = "https://github.com/dusk-network/dusk-blindbid", branch = "update_version"}
rand = "0.7"
