[package]
name = "transfer-circuits"
version = "0.1.0"
authors = ["Bounce23 <luke@dusk.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phoenix-core = { git = "https://github.com/dusk-network/phoenix-core" }
poseidon252 = { git = "https://github.com/dusk-network/Poseidon252" , tag = "v0.6.3"}
rand = "0.7"
kelvin = "0.18"
plonk_gadgets = {git = "https://github.com/dusk-network/plonk_gadgets", tag = "v0.2.0"}
dusk-pki = { git = "https://github.com/dusk-network/dusk-pki", tag = "v0.1.0" }
anyhow = "1.0"

[dependencies.dusk-plonk]
version = "0.2.9"
# features = ["trace-print", "trace"]