[package]
name = "transfer-circuits"
version = "0.1.0"
authors = ["Bounce23 <luke@dusk.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phoenix-core = { git = "https://github.com/dusk-network/phoenix-core" }
dusk-plonk = "0.2.8"
dusk-bls12_381 = "0.1.3"
dusk-jubjub = { git = "https://github.com/dusk-network/jubjub.git" , tag = "v0.3.6"}
